appName = "flo_assessment"

[mysql]
host = "127.0.0.1"
user = "user"
password = "password"
dbName = "db_name"
port = 3306

[redis]
urls = "127.0.0.1:6379"
password = "password"

[process]
concurrency = 9
jobqueuesize = 100
numworkers = 9
maxdbconnections = 100
maxdbidleconnections = 100